package com.ejulia.bookworm.service;

import com.ejulia.bookworm.model.User;
import com.ejulia.bookworm.dao.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class UserService {

    //Means to get the following bean (autogenerated bean userRepository, used to handle data)
    @Autowired
    private UserRepository userRepository;

    public void createUser(String name, String email) {

        User n = new User();
        n.setName(name);
        n.setEmail(email);

        // TODO : eg I will check there is not already a user registered with this email in our database

        userRepository.save(n);
    }

    public List<User> displayAllUsers() {

        return userRepository.findAll();
    }


}
