package com.ejulia.bookworm.service;

import com.ejulia.bookworm.model.User;
import com.ejulia.bookworm.dao.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class UserService {

    //Means to get the following bean (autogenerated bean userRepository, used to handle data)
    @Autowired
    private UserRepository userRepository;

    public String createUser(String firstName, String lastName, String phone, String email) {
        User n = new User();
        n.setFirstName(firstName);
        n.setLastName(lastName);
        n.setPhone(phone);
        n.setEmail(email);
        // TODO_suggestion : eg I will check there is not already a user registered with this email in our database
        userRepository.save(n);
        return "User registered";
    }

    public String deleteUser(Integer id)  {
        userRepository.deleteById(id);
        return "User deleted";
    }

    public List<User> displayAllUsers() {
        return userRepository.findAll();
    }


}
